package com.gaofen.dianying.persistent.mapper;

import com.gaofen.dianying.persistent.entity.TMovieDetail;
import com.gaofen.dianying.persistent.entity.TMovieDetailExample;
import com.gaofen.dianying.persistent.entity.TMovieDetailKey;
import com.gaofen.dianying.persistent.entity.TMovieDetailWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMovieDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    int countByExample(TMovieDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    int deleteByExample(TMovieDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TMovieDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    int insert(TMovieDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    int insertSelective(TMovieDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    List<TMovieDetailWithBLOBs> selectByExampleWithBLOBs(TMovieDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    List<TMovieDetail> selectByExample(TMovieDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    TMovieDetailWithBLOBs selectByPrimaryKey(TMovieDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TMovieDetailWithBLOBs record, @Param("example") TMovieDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TMovieDetailWithBLOBs record, @Param("example") TMovieDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TMovieDetail record, @Param("example") TMovieDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TMovieDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TMovieDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TMovieDetail record);
}