package com.gaofen.dianying.persistent.mapper;

import com.gaofen.dianying.persistent.entity.TMovieBaiduyun;
import com.gaofen.dianying.persistent.entity.TMovieBaiduyunExample;
import com.gaofen.dianying.persistent.entity.TMovieBaiduyunKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMovieBaiduyunMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_baiduyun
     *
     * @mbggenerated
     */
    int countByExample(TMovieBaiduyunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_baiduyun
     *
     * @mbggenerated
     */
    int deleteByExample(TMovieBaiduyunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_baiduyun
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TMovieBaiduyunKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_baiduyun
     *
     * @mbggenerated
     */
    int insert(TMovieBaiduyun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_baiduyun
     *
     * @mbggenerated
     */
    int insertSelective(TMovieBaiduyun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_baiduyun
     *
     * @mbggenerated
     */
    List<TMovieBaiduyun> selectByExample(TMovieBaiduyunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_baiduyun
     *
     * @mbggenerated
     */
    TMovieBaiduyun selectByPrimaryKey(TMovieBaiduyunKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_baiduyun
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TMovieBaiduyun record, @Param("example") TMovieBaiduyunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_baiduyun
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TMovieBaiduyun record, @Param("example") TMovieBaiduyunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_baiduyun
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TMovieBaiduyun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_baiduyun
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TMovieBaiduyun record);
}