package com.gaofen.dianying.persistent.mapper;

import com.gaofen.dianying.persistent.entity.TMovieExcellentComment;
import com.gaofen.dianying.persistent.entity.TMovieExcellentCommentExample;
import com.gaofen.dianying.persistent.entity.TMovieExcellentCommentKey;
import com.gaofen.dianying.persistent.entity.TMovieExcellentCommentWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMovieExcellentCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_excellent_comment
     *
     * @mbggenerated
     */
    int countByExample(TMovieExcellentCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_excellent_comment
     *
     * @mbggenerated
     */
    int deleteByExample(TMovieExcellentCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_excellent_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TMovieExcellentCommentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_excellent_comment
     *
     * @mbggenerated
     */
    int insert(TMovieExcellentCommentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_excellent_comment
     *
     * @mbggenerated
     */
    int insertSelective(TMovieExcellentCommentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_excellent_comment
     *
     * @mbggenerated
     */
    List<TMovieExcellentCommentWithBLOBs> selectByExampleWithBLOBs(TMovieExcellentCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_excellent_comment
     *
     * @mbggenerated
     */
    List<TMovieExcellentComment> selectByExample(TMovieExcellentCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_excellent_comment
     *
     * @mbggenerated
     */
    TMovieExcellentCommentWithBLOBs selectByPrimaryKey(TMovieExcellentCommentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_excellent_comment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TMovieExcellentCommentWithBLOBs record, @Param("example") TMovieExcellentCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_excellent_comment
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TMovieExcellentCommentWithBLOBs record, @Param("example") TMovieExcellentCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_excellent_comment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TMovieExcellentComment record, @Param("example") TMovieExcellentCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_excellent_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TMovieExcellentCommentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_excellent_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TMovieExcellentCommentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_excellent_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TMovieExcellentComment record);
}