package com.gaofen.dianying.persistents.entity;

import java.util.Date;

public class TDbMovie extends TDbMovieKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_movie.db_id
     *
     * @mbggenerated
     */
    private Integer db_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_movie.db_score
     *
     * @mbggenerated
     */
    private String db_score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_movie.db_stars
     *
     * @mbggenerated
     */
    private Integer db_stars;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_movie.year
     *
     * @mbggenerated
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_movie.images
     *
     * @mbggenerated
     */
    private String images;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_movie.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_movie.countries
     *
     * @mbggenerated
     */
    private String countries;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_movie.genres
     *
     * @mbggenerated
     */
    private String genres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_movie.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_movie.director
     *
     * @mbggenerated
     */
    private String director;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_movie.starring
     *
     * @mbggenerated
     */
    private String starring;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_movie.film_review
     *
     * @mbggenerated
     */
    private String film_review;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_movie.like_num
     *
     * @mbggenerated
     */
    private Integer like_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_movie.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_movie.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_movie.create_time
     *
     * @mbggenerated
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_db_movie.update_time
     *
     * @mbggenerated
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_movie.db_id
     *
     * @return the value of t_db_movie.db_id
     *
     * @mbggenerated
     */
    public Integer getDb_id() {
        return db_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_movie.db_id
     *
     * @param db_id the value for t_db_movie.db_id
     *
     * @mbggenerated
     */
    public void setDb_id(Integer db_id) {
        this.db_id = db_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_movie.db_score
     *
     * @return the value of t_db_movie.db_score
     *
     * @mbggenerated
     */
    public String getDb_score() {
        return db_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_movie.db_score
     *
     * @param db_score the value for t_db_movie.db_score
     *
     * @mbggenerated
     */
    public void setDb_score(String db_score) {
        this.db_score = db_score == null ? null : db_score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_movie.db_stars
     *
     * @return the value of t_db_movie.db_stars
     *
     * @mbggenerated
     */
    public Integer getDb_stars() {
        return db_stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_movie.db_stars
     *
     * @param db_stars the value for t_db_movie.db_stars
     *
     * @mbggenerated
     */
    public void setDb_stars(Integer db_stars) {
        this.db_stars = db_stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_movie.year
     *
     * @return the value of t_db_movie.year
     *
     * @mbggenerated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_movie.year
     *
     * @param year the value for t_db_movie.year
     *
     * @mbggenerated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_movie.images
     *
     * @return the value of t_db_movie.images
     *
     * @mbggenerated
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_movie.images
     *
     * @param images the value for t_db_movie.images
     *
     * @mbggenerated
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_movie.title
     *
     * @return the value of t_db_movie.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_movie.title
     *
     * @param title the value for t_db_movie.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_movie.countries
     *
     * @return the value of t_db_movie.countries
     *
     * @mbggenerated
     */
    public String getCountries() {
        return countries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_movie.countries
     *
     * @param countries the value for t_db_movie.countries
     *
     * @mbggenerated
     */
    public void setCountries(String countries) {
        this.countries = countries == null ? null : countries.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_movie.genres
     *
     * @return the value of t_db_movie.genres
     *
     * @mbggenerated
     */
    public String getGenres() {
        return genres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_movie.genres
     *
     * @param genres the value for t_db_movie.genres
     *
     * @mbggenerated
     */
    public void setGenres(String genres) {
        this.genres = genres == null ? null : genres.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_movie.type
     *
     * @return the value of t_db_movie.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_movie.type
     *
     * @param type the value for t_db_movie.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_movie.director
     *
     * @return the value of t_db_movie.director
     *
     * @mbggenerated
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_movie.director
     *
     * @param director the value for t_db_movie.director
     *
     * @mbggenerated
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_movie.starring
     *
     * @return the value of t_db_movie.starring
     *
     * @mbggenerated
     */
    public String getStarring() {
        return starring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_movie.starring
     *
     * @param starring the value for t_db_movie.starring
     *
     * @mbggenerated
     */
    public void setStarring(String starring) {
        this.starring = starring == null ? null : starring.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_movie.film_review
     *
     * @return the value of t_db_movie.film_review
     *
     * @mbggenerated
     */
    public String getFilm_review() {
        return film_review;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_movie.film_review
     *
     * @param film_review the value for t_db_movie.film_review
     *
     * @mbggenerated
     */
    public void setFilm_review(String film_review) {
        this.film_review = film_review == null ? null : film_review.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_movie.like_num
     *
     * @return the value of t_db_movie.like_num
     *
     * @mbggenerated
     */
    public Integer getLike_num() {
        return like_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_movie.like_num
     *
     * @param like_num the value for t_db_movie.like_num
     *
     * @mbggenerated
     */
    public void setLike_num(Integer like_num) {
        this.like_num = like_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_movie.status
     *
     * @return the value of t_db_movie.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_movie.status
     *
     * @param status the value for t_db_movie.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_movie.flag
     *
     * @return the value of t_db_movie.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_movie.flag
     *
     * @param flag the value for t_db_movie.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_movie.create_time
     *
     * @return the value of t_db_movie.create_time
     *
     * @mbggenerated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_movie.create_time
     *
     * @param create_time the value for t_db_movie.create_time
     *
     * @mbggenerated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_db_movie.update_time
     *
     * @return the value of t_db_movie.update_time
     *
     * @mbggenerated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_db_movie.update_time
     *
     * @param update_time the value for t_db_movie.update_time
     *
     * @mbggenerated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}