package com.gaofen.dianying.persistents.entity;

import java.util.Date;

public class TMovieConfig extends TMovieConfigKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_config.movie_enum_id
     *
     * @mbggenerated
     */
    private Integer movie_enum_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_config.movie_category
     *
     * @mbggenerated
     */
    private String movie_category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_config.movie_ids
     *
     * @mbggenerated
     */
    private String movie_ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_config.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_config.create_time
     *
     * @mbggenerated
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_config.update_time
     *
     * @mbggenerated
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_config.movie_enum_id
     *
     * @return the value of t_movie_config.movie_enum_id
     *
     * @mbggenerated
     */
    public Integer getMovie_enum_id() {
        return movie_enum_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_config.movie_enum_id
     *
     * @param movie_enum_id the value for t_movie_config.movie_enum_id
     *
     * @mbggenerated
     */
    public void setMovie_enum_id(Integer movie_enum_id) {
        this.movie_enum_id = movie_enum_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_config.movie_category
     *
     * @return the value of t_movie_config.movie_category
     *
     * @mbggenerated
     */
    public String getMovie_category() {
        return movie_category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_config.movie_category
     *
     * @param movie_category the value for t_movie_config.movie_category
     *
     * @mbggenerated
     */
    public void setMovie_category(String movie_category) {
        this.movie_category = movie_category == null ? null : movie_category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_config.movie_ids
     *
     * @return the value of t_movie_config.movie_ids
     *
     * @mbggenerated
     */
    public String getMovie_ids() {
        return movie_ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_config.movie_ids
     *
     * @param movie_ids the value for t_movie_config.movie_ids
     *
     * @mbggenerated
     */
    public void setMovie_ids(String movie_ids) {
        this.movie_ids = movie_ids == null ? null : movie_ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_config.flag
     *
     * @return the value of t_movie_config.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_config.flag
     *
     * @param flag the value for t_movie_config.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_config.create_time
     *
     * @return the value of t_movie_config.create_time
     *
     * @mbggenerated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_config.create_time
     *
     * @param create_time the value for t_movie_config.create_time
     *
     * @mbggenerated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_config.update_time
     *
     * @return the value of t_movie_config.update_time
     *
     * @mbggenerated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_config.update_time
     *
     * @param update_time the value for t_movie_config.update_time
     *
     * @mbggenerated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}