package com.gaofen.dianying.persistents.entity;

import java.util.Date;

public class TMovieStars extends TMovieStarsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_stars.movie_id
     *
     * @mbggenerated
     */
    private Integer movie_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_stars.star_name
     *
     * @mbggenerated
     */
    private String star_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_stars.role_name
     *
     * @mbggenerated
     */
    private String role_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_stars.pic_url
     *
     * @mbggenerated
     */
    private String pic_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_stars.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_stars.create_time
     *
     * @mbggenerated
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_stars.update_time
     *
     * @mbggenerated
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_stars.movie_id
     *
     * @return the value of t_movie_stars.movie_id
     *
     * @mbggenerated
     */
    public Integer getMovie_id() {
        return movie_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_stars.movie_id
     *
     * @param movie_id the value for t_movie_stars.movie_id
     *
     * @mbggenerated
     */
    public void setMovie_id(Integer movie_id) {
        this.movie_id = movie_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_stars.star_name
     *
     * @return the value of t_movie_stars.star_name
     *
     * @mbggenerated
     */
    public String getStar_name() {
        return star_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_stars.star_name
     *
     * @param star_name the value for t_movie_stars.star_name
     *
     * @mbggenerated
     */
    public void setStar_name(String star_name) {
        this.star_name = star_name == null ? null : star_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_stars.role_name
     *
     * @return the value of t_movie_stars.role_name
     *
     * @mbggenerated
     */
    public String getRole_name() {
        return role_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_stars.role_name
     *
     * @param role_name the value for t_movie_stars.role_name
     *
     * @mbggenerated
     */
    public void setRole_name(String role_name) {
        this.role_name = role_name == null ? null : role_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_stars.pic_url
     *
     * @return the value of t_movie_stars.pic_url
     *
     * @mbggenerated
     */
    public String getPic_url() {
        return pic_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_stars.pic_url
     *
     * @param pic_url the value for t_movie_stars.pic_url
     *
     * @mbggenerated
     */
    public void setPic_url(String pic_url) {
        this.pic_url = pic_url == null ? null : pic_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_stars.flag
     *
     * @return the value of t_movie_stars.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_stars.flag
     *
     * @param flag the value for t_movie_stars.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_stars.create_time
     *
     * @return the value of t_movie_stars.create_time
     *
     * @mbggenerated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_stars.create_time
     *
     * @param create_time the value for t_movie_stars.create_time
     *
     * @mbggenerated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_stars.update_time
     *
     * @return the value of t_movie_stars.update_time
     *
     * @mbggenerated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_stars.update_time
     *
     * @param update_time the value for t_movie_stars.update_time
     *
     * @mbggenerated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}