package com.gaofen.dianying.persistents.entity;

public class TMovieCommentsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_comments.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_comments.id
     *
     * @return the value of t_movie_comments.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_comments.id
     *
     * @param id the value for t_movie_comments.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}