package com.gaofen.dianying.persistents.entity;

import java.util.Date;

public class TMovieComments extends TMovieCommentsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_comments.movie_id
     *
     * @mbggenerated
     */
    private Integer movie_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_comments.comment_contents
     *
     * @mbggenerated
     */
    private String comment_contents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_comments.comment_name
     *
     * @mbggenerated
     */
    private String comment_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_comments.db_score
     *
     * @mbggenerated
     */
    private String db_score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_comments.pic_url
     *
     * @mbggenerated
     */
    private String pic_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_comments.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_comments.create_time
     *
     * @mbggenerated
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_comments.update_time
     *
     * @mbggenerated
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_comments.movie_id
     *
     * @return the value of t_movie_comments.movie_id
     *
     * @mbggenerated
     */
    public Integer getMovie_id() {
        return movie_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_comments.movie_id
     *
     * @param movie_id the value for t_movie_comments.movie_id
     *
     * @mbggenerated
     */
    public void setMovie_id(Integer movie_id) {
        this.movie_id = movie_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_comments.comment_contents
     *
     * @return the value of t_movie_comments.comment_contents
     *
     * @mbggenerated
     */
    public String getComment_contents() {
        return comment_contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_comments.comment_contents
     *
     * @param comment_contents the value for t_movie_comments.comment_contents
     *
     * @mbggenerated
     */
    public void setComment_contents(String comment_contents) {
        this.comment_contents = comment_contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_comments.comment_name
     *
     * @return the value of t_movie_comments.comment_name
     *
     * @mbggenerated
     */
    public String getComment_name() {
        return comment_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_comments.comment_name
     *
     * @param comment_name the value for t_movie_comments.comment_name
     *
     * @mbggenerated
     */
    public void setComment_name(String comment_name) {
        this.comment_name = comment_name == null ? null : comment_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_comments.db_score
     *
     * @return the value of t_movie_comments.db_score
     *
     * @mbggenerated
     */
    public String getDb_score() {
        return db_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_comments.db_score
     *
     * @param db_score the value for t_movie_comments.db_score
     *
     * @mbggenerated
     */
    public void setDb_score(String db_score) {
        this.db_score = db_score == null ? null : db_score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_comments.pic_url
     *
     * @return the value of t_movie_comments.pic_url
     *
     * @mbggenerated
     */
    public String getPic_url() {
        return pic_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_comments.pic_url
     *
     * @param pic_url the value for t_movie_comments.pic_url
     *
     * @mbggenerated
     */
    public void setPic_url(String pic_url) {
        this.pic_url = pic_url == null ? null : pic_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_comments.flag
     *
     * @return the value of t_movie_comments.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_comments.flag
     *
     * @param flag the value for t_movie_comments.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_comments.create_time
     *
     * @return the value of t_movie_comments.create_time
     *
     * @mbggenerated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_comments.create_time
     *
     * @param create_time the value for t_movie_comments.create_time
     *
     * @mbggenerated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_comments.update_time
     *
     * @return the value of t_movie_comments.update_time
     *
     * @mbggenerated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_comments.update_time
     *
     * @param update_time the value for t_movie_comments.update_time
     *
     * @mbggenerated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}