package com.gaofen.dianying.persistents.entity;

import java.util.Date;

public class TMoviePhotos extends TMoviePhotosKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_photos.movie_id
     *
     * @mbggenerated
     */
    private Integer movie_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_photos.pic_url
     *
     * @mbggenerated
     */
    private String pic_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_photos.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_photos.create_time
     *
     * @mbggenerated
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_photos.update_time
     *
     * @mbggenerated
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_photos.movie_id
     *
     * @return the value of t_movie_photos.movie_id
     *
     * @mbggenerated
     */
    public Integer getMovie_id() {
        return movie_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_photos.movie_id
     *
     * @param movie_id the value for t_movie_photos.movie_id
     *
     * @mbggenerated
     */
    public void setMovie_id(Integer movie_id) {
        this.movie_id = movie_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_photos.pic_url
     *
     * @return the value of t_movie_photos.pic_url
     *
     * @mbggenerated
     */
    public String getPic_url() {
        return pic_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_photos.pic_url
     *
     * @param pic_url the value for t_movie_photos.pic_url
     *
     * @mbggenerated
     */
    public void setPic_url(String pic_url) {
        this.pic_url = pic_url == null ? null : pic_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_photos.flag
     *
     * @return the value of t_movie_photos.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_photos.flag
     *
     * @param flag the value for t_movie_photos.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_photos.create_time
     *
     * @return the value of t_movie_photos.create_time
     *
     * @mbggenerated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_photos.create_time
     *
     * @param create_time the value for t_movie_photos.create_time
     *
     * @mbggenerated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_photos.update_time
     *
     * @return the value of t_movie_photos.update_time
     *
     * @mbggenerated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_photos.update_time
     *
     * @param update_time the value for t_movie_photos.update_time
     *
     * @mbggenerated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}