package com.gaofen.dianying.persistent.entity;

public class TMovieDetailWithBLOBs extends TMovieDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_detail.movie_synopsis
     *
     * @mbggenerated
     */
    private String movie_synopsis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_detail.movie_stills
     *
     * @mbggenerated
     */
    private String movie_stills;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_detail.movie_synopsis
     *
     * @return the value of t_movie_detail.movie_synopsis
     *
     * @mbggenerated
     */
    public String getMovie_synopsis() {
        return movie_synopsis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_detail.movie_synopsis
     *
     * @param movie_synopsis the value for t_movie_detail.movie_synopsis
     *
     * @mbggenerated
     */
    public void setMovie_synopsis(String movie_synopsis) {
        this.movie_synopsis = movie_synopsis == null ? null : movie_synopsis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_detail.movie_stills
     *
     * @return the value of t_movie_detail.movie_stills
     *
     * @mbggenerated
     */
    public String getMovie_stills() {
        return movie_stills;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_detail.movie_stills
     *
     * @param movie_stills the value for t_movie_detail.movie_stills
     *
     * @mbggenerated
     */
    public void setMovie_stills(String movie_stills) {
        this.movie_stills = movie_stills == null ? null : movie_stills.trim();
    }
}