package com.gaofen.dianying.persistent.entity;

import java.util.Date;

public class TMovieDetail extends TMovieDetailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_detail.movie_id
     *
     * @mbggenerated
     */
    private Integer movie_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_detail.movie_like_num
     *
     * @mbggenerated
     */
    private Integer movie_like_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_detail.create_time
     *
     * @mbggenerated
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_detail.update_time
     *
     * @mbggenerated
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_detail.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_detail.movie_id
     *
     * @return the value of t_movie_detail.movie_id
     *
     * @mbggenerated
     */
    public Integer getMovie_id() {
        return movie_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_detail.movie_id
     *
     * @param movie_id the value for t_movie_detail.movie_id
     *
     * @mbggenerated
     */
    public void setMovie_id(Integer movie_id) {
        this.movie_id = movie_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_detail.movie_like_num
     *
     * @return the value of t_movie_detail.movie_like_num
     *
     * @mbggenerated
     */
    public Integer getMovie_like_num() {
        return movie_like_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_detail.movie_like_num
     *
     * @param movie_like_num the value for t_movie_detail.movie_like_num
     *
     * @mbggenerated
     */
    public void setMovie_like_num(Integer movie_like_num) {
        this.movie_like_num = movie_like_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_detail.create_time
     *
     * @return the value of t_movie_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_detail.create_time
     *
     * @param create_time the value for t_movie_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_detail.update_time
     *
     * @return the value of t_movie_detail.update_time
     *
     * @mbggenerated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_detail.update_time
     *
     * @param update_time the value for t_movie_detail.update_time
     *
     * @mbggenerated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_detail.flag
     *
     * @return the value of t_movie_detail.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_detail.flag
     *
     * @param flag the value for t_movie_detail.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}