package com.gaofen.dianying.persistent.entity;

import java.util.Date;

public class TMovieExcellentComment extends TMovieExcellentCommentKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_excellent_comment.movie_id
     *
     * @mbggenerated
     */
    private Integer movie_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_excellent_comment.movie_excellent_comment_author
     *
     * @mbggenerated
     */
    private String movie_excellent_comment_author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_excellent_comment.create_time
     *
     * @mbggenerated
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_excellent_comment.update_time
     *
     * @mbggenerated
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_excellent_comment.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_excellent_comment.movie_id
     *
     * @return the value of t_movie_excellent_comment.movie_id
     *
     * @mbggenerated
     */
    public Integer getMovie_id() {
        return movie_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_excellent_comment.movie_id
     *
     * @param movie_id the value for t_movie_excellent_comment.movie_id
     *
     * @mbggenerated
     */
    public void setMovie_id(Integer movie_id) {
        this.movie_id = movie_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_excellent_comment.movie_excellent_comment_author
     *
     * @return the value of t_movie_excellent_comment.movie_excellent_comment_author
     *
     * @mbggenerated
     */
    public String getMovie_excellent_comment_author() {
        return movie_excellent_comment_author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_excellent_comment.movie_excellent_comment_author
     *
     * @param movie_excellent_comment_author the value for t_movie_excellent_comment.movie_excellent_comment_author
     *
     * @mbggenerated
     */
    public void setMovie_excellent_comment_author(String movie_excellent_comment_author) {
        this.movie_excellent_comment_author = movie_excellent_comment_author == null ? null : movie_excellent_comment_author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_excellent_comment.create_time
     *
     * @return the value of t_movie_excellent_comment.create_time
     *
     * @mbggenerated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_excellent_comment.create_time
     *
     * @param create_time the value for t_movie_excellent_comment.create_time
     *
     * @mbggenerated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_excellent_comment.update_time
     *
     * @return the value of t_movie_excellent_comment.update_time
     *
     * @mbggenerated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_excellent_comment.update_time
     *
     * @param update_time the value for t_movie_excellent_comment.update_time
     *
     * @mbggenerated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_excellent_comment.flag
     *
     * @return the value of t_movie_excellent_comment.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_excellent_comment.flag
     *
     * @param flag the value for t_movie_excellent_comment.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}