package com.gaofen.dianying.persistent.entity;

public class TMovieKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie.movie_id
     *
     * @mbggenerated
     */
    private Integer movie_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie.movie_id
     *
     * @return the value of t_movie.movie_id
     *
     * @mbggenerated
     */
    public Integer getMovie_id() {
        return movie_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie.movie_id
     *
     * @param movie_id the value for t_movie.movie_id
     *
     * @mbggenerated
     */
    public void setMovie_id(Integer movie_id) {
        this.movie_id = movie_id;
    }
}