package com.gaofen.dianying.persistent.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TMovieDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    public TMovieDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMovie_detail_idIsNull() {
            addCriterion("movie_detail_id is null");
            return (Criteria) this;
        }

        public Criteria andMovie_detail_idIsNotNull() {
            addCriterion("movie_detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andMovie_detail_idEqualTo(Integer value) {
            addCriterion("movie_detail_id =", value, "movie_detail_id");
            return (Criteria) this;
        }

        public Criteria andMovie_detail_idNotEqualTo(Integer value) {
            addCriterion("movie_detail_id <>", value, "movie_detail_id");
            return (Criteria) this;
        }

        public Criteria andMovie_detail_idGreaterThan(Integer value) {
            addCriterion("movie_detail_id >", value, "movie_detail_id");
            return (Criteria) this;
        }

        public Criteria andMovie_detail_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("movie_detail_id >=", value, "movie_detail_id");
            return (Criteria) this;
        }

        public Criteria andMovie_detail_idLessThan(Integer value) {
            addCriterion("movie_detail_id <", value, "movie_detail_id");
            return (Criteria) this;
        }

        public Criteria andMovie_detail_idLessThanOrEqualTo(Integer value) {
            addCriterion("movie_detail_id <=", value, "movie_detail_id");
            return (Criteria) this;
        }

        public Criteria andMovie_detail_idIn(List<Integer> values) {
            addCriterion("movie_detail_id in", values, "movie_detail_id");
            return (Criteria) this;
        }

        public Criteria andMovie_detail_idNotIn(List<Integer> values) {
            addCriterion("movie_detail_id not in", values, "movie_detail_id");
            return (Criteria) this;
        }

        public Criteria andMovie_detail_idBetween(Integer value1, Integer value2) {
            addCriterion("movie_detail_id between", value1, value2, "movie_detail_id");
            return (Criteria) this;
        }

        public Criteria andMovie_detail_idNotBetween(Integer value1, Integer value2) {
            addCriterion("movie_detail_id not between", value1, value2, "movie_detail_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idIsNull() {
            addCriterion("movie_id is null");
            return (Criteria) this;
        }

        public Criteria andMovie_idIsNotNull() {
            addCriterion("movie_id is not null");
            return (Criteria) this;
        }

        public Criteria andMovie_idEqualTo(Integer value) {
            addCriterion("movie_id =", value, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idNotEqualTo(Integer value) {
            addCriterion("movie_id <>", value, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idGreaterThan(Integer value) {
            addCriterion("movie_id >", value, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("movie_id >=", value, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idLessThan(Integer value) {
            addCriterion("movie_id <", value, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idLessThanOrEqualTo(Integer value) {
            addCriterion("movie_id <=", value, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idIn(List<Integer> values) {
            addCriterion("movie_id in", values, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idNotIn(List<Integer> values) {
            addCriterion("movie_id not in", values, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idBetween(Integer value1, Integer value2) {
            addCriterion("movie_id between", value1, value2, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idNotBetween(Integer value1, Integer value2) {
            addCriterion("movie_id not between", value1, value2, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_like_numIsNull() {
            addCriterion("movie_like_num is null");
            return (Criteria) this;
        }

        public Criteria andMovie_like_numIsNotNull() {
            addCriterion("movie_like_num is not null");
            return (Criteria) this;
        }

        public Criteria andMovie_like_numEqualTo(Integer value) {
            addCriterion("movie_like_num =", value, "movie_like_num");
            return (Criteria) this;
        }

        public Criteria andMovie_like_numNotEqualTo(Integer value) {
            addCriterion("movie_like_num <>", value, "movie_like_num");
            return (Criteria) this;
        }

        public Criteria andMovie_like_numGreaterThan(Integer value) {
            addCriterion("movie_like_num >", value, "movie_like_num");
            return (Criteria) this;
        }

        public Criteria andMovie_like_numGreaterThanOrEqualTo(Integer value) {
            addCriterion("movie_like_num >=", value, "movie_like_num");
            return (Criteria) this;
        }

        public Criteria andMovie_like_numLessThan(Integer value) {
            addCriterion("movie_like_num <", value, "movie_like_num");
            return (Criteria) this;
        }

        public Criteria andMovie_like_numLessThanOrEqualTo(Integer value) {
            addCriterion("movie_like_num <=", value, "movie_like_num");
            return (Criteria) this;
        }

        public Criteria andMovie_like_numIn(List<Integer> values) {
            addCriterion("movie_like_num in", values, "movie_like_num");
            return (Criteria) this;
        }

        public Criteria andMovie_like_numNotIn(List<Integer> values) {
            addCriterion("movie_like_num not in", values, "movie_like_num");
            return (Criteria) this;
        }

        public Criteria andMovie_like_numBetween(Integer value1, Integer value2) {
            addCriterion("movie_like_num between", value1, value2, "movie_like_num");
            return (Criteria) this;
        }

        public Criteria andMovie_like_numNotBetween(Integer value1, Integer value2) {
            addCriterion("movie_like_num not between", value1, value2, "movie_like_num");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeEqualTo(Date value) {
            addCriterion("update_time =", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThan(Date value) {
            addCriterion("update_time >", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThan(Date value) {
            addCriterion("update_time <", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIn(List<Date> values) {
            addCriterion("update_time in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("flag is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("flag is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(Integer value) {
            addCriterion("flag =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(Integer value) {
            addCriterion("flag <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(Integer value) {
            addCriterion("flag >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("flag >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(Integer value) {
            addCriterion("flag <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(Integer value) {
            addCriterion("flag <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<Integer> values) {
            addCriterion("flag in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<Integer> values) {
            addCriterion("flag not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(Integer value1, Integer value2) {
            addCriterion("flag between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("flag not between", value1, value2, "flag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_movie_detail
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_movie_detail
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}