package com.gaofen.dianying.persistent.entity;

import java.util.Date;

public class TMovie extends TMovieKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie.movie_name
     *
     * @mbggenerated
     */
    private String movie_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie.movie_director
     *
     * @mbggenerated
     */
    private String movie_director;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie.movie_directedBy
     *
     * @mbggenerated
     */
    private String movie_directedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie.movie_starring
     *
     * @mbggenerated
     */
    private String movie_starring;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie.movie_country
     *
     * @mbggenerated
     */
    private String movie_country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie.movie_language
     *
     * @mbggenerated
     */
    private String movie_language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie.movie_type
     *
     * @mbggenerated
     */
    private Integer movie_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie.movie_rating
     *
     * @mbggenerated
     */
    private Integer movie_rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie.movie_quote
     *
     * @mbggenerated
     */
    private String movie_quote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie.movie_cover_pic
     *
     * @mbggenerated
     */
    private String movie_cover_pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie.release_time
     *
     * @mbggenerated
     */
    private Date release_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie.create_time
     *
     * @mbggenerated
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie.update_time
     *
     * @mbggenerated
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie.movie_name
     *
     * @return the value of t_movie.movie_name
     *
     * @mbggenerated
     */
    public String getMovie_name() {
        return movie_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie.movie_name
     *
     * @param movie_name the value for t_movie.movie_name
     *
     * @mbggenerated
     */
    public void setMovie_name(String movie_name) {
        this.movie_name = movie_name == null ? null : movie_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie.movie_director
     *
     * @return the value of t_movie.movie_director
     *
     * @mbggenerated
     */
    public String getMovie_director() {
        return movie_director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie.movie_director
     *
     * @param movie_director the value for t_movie.movie_director
     *
     * @mbggenerated
     */
    public void setMovie_director(String movie_director) {
        this.movie_director = movie_director == null ? null : movie_director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie.movie_directedBy
     *
     * @return the value of t_movie.movie_directedBy
     *
     * @mbggenerated
     */
    public String getMovie_directedBy() {
        return movie_directedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie.movie_directedBy
     *
     * @param movie_directedBy the value for t_movie.movie_directedBy
     *
     * @mbggenerated
     */
    public void setMovie_directedBy(String movie_directedBy) {
        this.movie_directedBy = movie_directedBy == null ? null : movie_directedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie.movie_starring
     *
     * @return the value of t_movie.movie_starring
     *
     * @mbggenerated
     */
    public String getMovie_starring() {
        return movie_starring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie.movie_starring
     *
     * @param movie_starring the value for t_movie.movie_starring
     *
     * @mbggenerated
     */
    public void setMovie_starring(String movie_starring) {
        this.movie_starring = movie_starring == null ? null : movie_starring.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie.movie_country
     *
     * @return the value of t_movie.movie_country
     *
     * @mbggenerated
     */
    public String getMovie_country() {
        return movie_country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie.movie_country
     *
     * @param movie_country the value for t_movie.movie_country
     *
     * @mbggenerated
     */
    public void setMovie_country(String movie_country) {
        this.movie_country = movie_country == null ? null : movie_country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie.movie_language
     *
     * @return the value of t_movie.movie_language
     *
     * @mbggenerated
     */
    public String getMovie_language() {
        return movie_language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie.movie_language
     *
     * @param movie_language the value for t_movie.movie_language
     *
     * @mbggenerated
     */
    public void setMovie_language(String movie_language) {
        this.movie_language = movie_language == null ? null : movie_language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie.movie_type
     *
     * @return the value of t_movie.movie_type
     *
     * @mbggenerated
     */
    public Integer getMovie_type() {
        return movie_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie.movie_type
     *
     * @param movie_type the value for t_movie.movie_type
     *
     * @mbggenerated
     */
    public void setMovie_type(Integer movie_type) {
        this.movie_type = movie_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie.movie_rating
     *
     * @return the value of t_movie.movie_rating
     *
     * @mbggenerated
     */
    public Integer getMovie_rating() {
        return movie_rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie.movie_rating
     *
     * @param movie_rating the value for t_movie.movie_rating
     *
     * @mbggenerated
     */
    public void setMovie_rating(Integer movie_rating) {
        this.movie_rating = movie_rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie.movie_quote
     *
     * @return the value of t_movie.movie_quote
     *
     * @mbggenerated
     */
    public String getMovie_quote() {
        return movie_quote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie.movie_quote
     *
     * @param movie_quote the value for t_movie.movie_quote
     *
     * @mbggenerated
     */
    public void setMovie_quote(String movie_quote) {
        this.movie_quote = movie_quote == null ? null : movie_quote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie.movie_cover_pic
     *
     * @return the value of t_movie.movie_cover_pic
     *
     * @mbggenerated
     */
    public String getMovie_cover_pic() {
        return movie_cover_pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie.movie_cover_pic
     *
     * @param movie_cover_pic the value for t_movie.movie_cover_pic
     *
     * @mbggenerated
     */
    public void setMovie_cover_pic(String movie_cover_pic) {
        this.movie_cover_pic = movie_cover_pic == null ? null : movie_cover_pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie.release_time
     *
     * @return the value of t_movie.release_time
     *
     * @mbggenerated
     */
    public Date getRelease_time() {
        return release_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie.release_time
     *
     * @param release_time the value for t_movie.release_time
     *
     * @mbggenerated
     */
    public void setRelease_time(Date release_time) {
        this.release_time = release_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie.create_time
     *
     * @return the value of t_movie.create_time
     *
     * @mbggenerated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie.create_time
     *
     * @param create_time the value for t_movie.create_time
     *
     * @mbggenerated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie.update_time
     *
     * @return the value of t_movie.update_time
     *
     * @mbggenerated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie.update_time
     *
     * @param update_time the value for t_movie.update_time
     *
     * @mbggenerated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie.flag
     *
     * @return the value of t_movie.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie.flag
     *
     * @param flag the value for t_movie.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}