package com.gaofen.dianying.persistent.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TMovieExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_movie
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_movie
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_movie
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie
     *
     * @mbggenerated
     */
    public TMovieExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_movie
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMovie_idIsNull() {
            addCriterion("movie_id is null");
            return (Criteria) this;
        }

        public Criteria andMovie_idIsNotNull() {
            addCriterion("movie_id is not null");
            return (Criteria) this;
        }

        public Criteria andMovie_idEqualTo(Integer value) {
            addCriterion("movie_id =", value, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idNotEqualTo(Integer value) {
            addCriterion("movie_id <>", value, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idGreaterThan(Integer value) {
            addCriterion("movie_id >", value, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("movie_id >=", value, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idLessThan(Integer value) {
            addCriterion("movie_id <", value, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idLessThanOrEqualTo(Integer value) {
            addCriterion("movie_id <=", value, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idIn(List<Integer> values) {
            addCriterion("movie_id in", values, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idNotIn(List<Integer> values) {
            addCriterion("movie_id not in", values, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idBetween(Integer value1, Integer value2) {
            addCriterion("movie_id between", value1, value2, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_idNotBetween(Integer value1, Integer value2) {
            addCriterion("movie_id not between", value1, value2, "movie_id");
            return (Criteria) this;
        }

        public Criteria andMovie_nameIsNull() {
            addCriterion("movie_name is null");
            return (Criteria) this;
        }

        public Criteria andMovie_nameIsNotNull() {
            addCriterion("movie_name is not null");
            return (Criteria) this;
        }

        public Criteria andMovie_nameEqualTo(String value) {
            addCriterion("movie_name =", value, "movie_name");
            return (Criteria) this;
        }

        public Criteria andMovie_nameNotEqualTo(String value) {
            addCriterion("movie_name <>", value, "movie_name");
            return (Criteria) this;
        }

        public Criteria andMovie_nameGreaterThan(String value) {
            addCriterion("movie_name >", value, "movie_name");
            return (Criteria) this;
        }

        public Criteria andMovie_nameGreaterThanOrEqualTo(String value) {
            addCriterion("movie_name >=", value, "movie_name");
            return (Criteria) this;
        }

        public Criteria andMovie_nameLessThan(String value) {
            addCriterion("movie_name <", value, "movie_name");
            return (Criteria) this;
        }

        public Criteria andMovie_nameLessThanOrEqualTo(String value) {
            addCriterion("movie_name <=", value, "movie_name");
            return (Criteria) this;
        }

        public Criteria andMovie_nameLike(String value) {
            addCriterion("movie_name like", value, "movie_name");
            return (Criteria) this;
        }

        public Criteria andMovie_nameNotLike(String value) {
            addCriterion("movie_name not like", value, "movie_name");
            return (Criteria) this;
        }

        public Criteria andMovie_nameIn(List<String> values) {
            addCriterion("movie_name in", values, "movie_name");
            return (Criteria) this;
        }

        public Criteria andMovie_nameNotIn(List<String> values) {
            addCriterion("movie_name not in", values, "movie_name");
            return (Criteria) this;
        }

        public Criteria andMovie_nameBetween(String value1, String value2) {
            addCriterion("movie_name between", value1, value2, "movie_name");
            return (Criteria) this;
        }

        public Criteria andMovie_nameNotBetween(String value1, String value2) {
            addCriterion("movie_name not between", value1, value2, "movie_name");
            return (Criteria) this;
        }

        public Criteria andMovie_directorIsNull() {
            addCriterion("movie_director is null");
            return (Criteria) this;
        }

        public Criteria andMovie_directorIsNotNull() {
            addCriterion("movie_director is not null");
            return (Criteria) this;
        }

        public Criteria andMovie_directorEqualTo(String value) {
            addCriterion("movie_director =", value, "movie_director");
            return (Criteria) this;
        }

        public Criteria andMovie_directorNotEqualTo(String value) {
            addCriterion("movie_director <>", value, "movie_director");
            return (Criteria) this;
        }

        public Criteria andMovie_directorGreaterThan(String value) {
            addCriterion("movie_director >", value, "movie_director");
            return (Criteria) this;
        }

        public Criteria andMovie_directorGreaterThanOrEqualTo(String value) {
            addCriterion("movie_director >=", value, "movie_director");
            return (Criteria) this;
        }

        public Criteria andMovie_directorLessThan(String value) {
            addCriterion("movie_director <", value, "movie_director");
            return (Criteria) this;
        }

        public Criteria andMovie_directorLessThanOrEqualTo(String value) {
            addCriterion("movie_director <=", value, "movie_director");
            return (Criteria) this;
        }

        public Criteria andMovie_directorLike(String value) {
            addCriterion("movie_director like", value, "movie_director");
            return (Criteria) this;
        }

        public Criteria andMovie_directorNotLike(String value) {
            addCriterion("movie_director not like", value, "movie_director");
            return (Criteria) this;
        }

        public Criteria andMovie_directorIn(List<String> values) {
            addCriterion("movie_director in", values, "movie_director");
            return (Criteria) this;
        }

        public Criteria andMovie_directorNotIn(List<String> values) {
            addCriterion("movie_director not in", values, "movie_director");
            return (Criteria) this;
        }

        public Criteria andMovie_directorBetween(String value1, String value2) {
            addCriterion("movie_director between", value1, value2, "movie_director");
            return (Criteria) this;
        }

        public Criteria andMovie_directorNotBetween(String value1, String value2) {
            addCriterion("movie_director not between", value1, value2, "movie_director");
            return (Criteria) this;
        }

        public Criteria andMovie_directedByIsNull() {
            addCriterion("movie_directedBy is null");
            return (Criteria) this;
        }

        public Criteria andMovie_directedByIsNotNull() {
            addCriterion("movie_directedBy is not null");
            return (Criteria) this;
        }

        public Criteria andMovie_directedByEqualTo(String value) {
            addCriterion("movie_directedBy =", value, "movie_directedBy");
            return (Criteria) this;
        }

        public Criteria andMovie_directedByNotEqualTo(String value) {
            addCriterion("movie_directedBy <>", value, "movie_directedBy");
            return (Criteria) this;
        }

        public Criteria andMovie_directedByGreaterThan(String value) {
            addCriterion("movie_directedBy >", value, "movie_directedBy");
            return (Criteria) this;
        }

        public Criteria andMovie_directedByGreaterThanOrEqualTo(String value) {
            addCriterion("movie_directedBy >=", value, "movie_directedBy");
            return (Criteria) this;
        }

        public Criteria andMovie_directedByLessThan(String value) {
            addCriterion("movie_directedBy <", value, "movie_directedBy");
            return (Criteria) this;
        }

        public Criteria andMovie_directedByLessThanOrEqualTo(String value) {
            addCriterion("movie_directedBy <=", value, "movie_directedBy");
            return (Criteria) this;
        }

        public Criteria andMovie_directedByLike(String value) {
            addCriterion("movie_directedBy like", value, "movie_directedBy");
            return (Criteria) this;
        }

        public Criteria andMovie_directedByNotLike(String value) {
            addCriterion("movie_directedBy not like", value, "movie_directedBy");
            return (Criteria) this;
        }

        public Criteria andMovie_directedByIn(List<String> values) {
            addCriterion("movie_directedBy in", values, "movie_directedBy");
            return (Criteria) this;
        }

        public Criteria andMovie_directedByNotIn(List<String> values) {
            addCriterion("movie_directedBy not in", values, "movie_directedBy");
            return (Criteria) this;
        }

        public Criteria andMovie_directedByBetween(String value1, String value2) {
            addCriterion("movie_directedBy between", value1, value2, "movie_directedBy");
            return (Criteria) this;
        }

        public Criteria andMovie_directedByNotBetween(String value1, String value2) {
            addCriterion("movie_directedBy not between", value1, value2, "movie_directedBy");
            return (Criteria) this;
        }

        public Criteria andMovie_starringIsNull() {
            addCriterion("movie_starring is null");
            return (Criteria) this;
        }

        public Criteria andMovie_starringIsNotNull() {
            addCriterion("movie_starring is not null");
            return (Criteria) this;
        }

        public Criteria andMovie_starringEqualTo(String value) {
            addCriterion("movie_starring =", value, "movie_starring");
            return (Criteria) this;
        }

        public Criteria andMovie_starringNotEqualTo(String value) {
            addCriterion("movie_starring <>", value, "movie_starring");
            return (Criteria) this;
        }

        public Criteria andMovie_starringGreaterThan(String value) {
            addCriterion("movie_starring >", value, "movie_starring");
            return (Criteria) this;
        }

        public Criteria andMovie_starringGreaterThanOrEqualTo(String value) {
            addCriterion("movie_starring >=", value, "movie_starring");
            return (Criteria) this;
        }

        public Criteria andMovie_starringLessThan(String value) {
            addCriterion("movie_starring <", value, "movie_starring");
            return (Criteria) this;
        }

        public Criteria andMovie_starringLessThanOrEqualTo(String value) {
            addCriterion("movie_starring <=", value, "movie_starring");
            return (Criteria) this;
        }

        public Criteria andMovie_starringLike(String value) {
            addCriterion("movie_starring like", value, "movie_starring");
            return (Criteria) this;
        }

        public Criteria andMovie_starringNotLike(String value) {
            addCriterion("movie_starring not like", value, "movie_starring");
            return (Criteria) this;
        }

        public Criteria andMovie_starringIn(List<String> values) {
            addCriterion("movie_starring in", values, "movie_starring");
            return (Criteria) this;
        }

        public Criteria andMovie_starringNotIn(List<String> values) {
            addCriterion("movie_starring not in", values, "movie_starring");
            return (Criteria) this;
        }

        public Criteria andMovie_starringBetween(String value1, String value2) {
            addCriterion("movie_starring between", value1, value2, "movie_starring");
            return (Criteria) this;
        }

        public Criteria andMovie_starringNotBetween(String value1, String value2) {
            addCriterion("movie_starring not between", value1, value2, "movie_starring");
            return (Criteria) this;
        }

        public Criteria andMovie_countryIsNull() {
            addCriterion("movie_country is null");
            return (Criteria) this;
        }

        public Criteria andMovie_countryIsNotNull() {
            addCriterion("movie_country is not null");
            return (Criteria) this;
        }

        public Criteria andMovie_countryEqualTo(String value) {
            addCriterion("movie_country =", value, "movie_country");
            return (Criteria) this;
        }

        public Criteria andMovie_countryNotEqualTo(String value) {
            addCriterion("movie_country <>", value, "movie_country");
            return (Criteria) this;
        }

        public Criteria andMovie_countryGreaterThan(String value) {
            addCriterion("movie_country >", value, "movie_country");
            return (Criteria) this;
        }

        public Criteria andMovie_countryGreaterThanOrEqualTo(String value) {
            addCriterion("movie_country >=", value, "movie_country");
            return (Criteria) this;
        }

        public Criteria andMovie_countryLessThan(String value) {
            addCriterion("movie_country <", value, "movie_country");
            return (Criteria) this;
        }

        public Criteria andMovie_countryLessThanOrEqualTo(String value) {
            addCriterion("movie_country <=", value, "movie_country");
            return (Criteria) this;
        }

        public Criteria andMovie_countryLike(String value) {
            addCriterion("movie_country like", value, "movie_country");
            return (Criteria) this;
        }

        public Criteria andMovie_countryNotLike(String value) {
            addCriterion("movie_country not like", value, "movie_country");
            return (Criteria) this;
        }

        public Criteria andMovie_countryIn(List<String> values) {
            addCriterion("movie_country in", values, "movie_country");
            return (Criteria) this;
        }

        public Criteria andMovie_countryNotIn(List<String> values) {
            addCriterion("movie_country not in", values, "movie_country");
            return (Criteria) this;
        }

        public Criteria andMovie_countryBetween(String value1, String value2) {
            addCriterion("movie_country between", value1, value2, "movie_country");
            return (Criteria) this;
        }

        public Criteria andMovie_countryNotBetween(String value1, String value2) {
            addCriterion("movie_country not between", value1, value2, "movie_country");
            return (Criteria) this;
        }

        public Criteria andMovie_languageIsNull() {
            addCriterion("movie_language is null");
            return (Criteria) this;
        }

        public Criteria andMovie_languageIsNotNull() {
            addCriterion("movie_language is not null");
            return (Criteria) this;
        }

        public Criteria andMovie_languageEqualTo(String value) {
            addCriterion("movie_language =", value, "movie_language");
            return (Criteria) this;
        }

        public Criteria andMovie_languageNotEqualTo(String value) {
            addCriterion("movie_language <>", value, "movie_language");
            return (Criteria) this;
        }

        public Criteria andMovie_languageGreaterThan(String value) {
            addCriterion("movie_language >", value, "movie_language");
            return (Criteria) this;
        }

        public Criteria andMovie_languageGreaterThanOrEqualTo(String value) {
            addCriterion("movie_language >=", value, "movie_language");
            return (Criteria) this;
        }

        public Criteria andMovie_languageLessThan(String value) {
            addCriterion("movie_language <", value, "movie_language");
            return (Criteria) this;
        }

        public Criteria andMovie_languageLessThanOrEqualTo(String value) {
            addCriterion("movie_language <=", value, "movie_language");
            return (Criteria) this;
        }

        public Criteria andMovie_languageLike(String value) {
            addCriterion("movie_language like", value, "movie_language");
            return (Criteria) this;
        }

        public Criteria andMovie_languageNotLike(String value) {
            addCriterion("movie_language not like", value, "movie_language");
            return (Criteria) this;
        }

        public Criteria andMovie_languageIn(List<String> values) {
            addCriterion("movie_language in", values, "movie_language");
            return (Criteria) this;
        }

        public Criteria andMovie_languageNotIn(List<String> values) {
            addCriterion("movie_language not in", values, "movie_language");
            return (Criteria) this;
        }

        public Criteria andMovie_languageBetween(String value1, String value2) {
            addCriterion("movie_language between", value1, value2, "movie_language");
            return (Criteria) this;
        }

        public Criteria andMovie_languageNotBetween(String value1, String value2) {
            addCriterion("movie_language not between", value1, value2, "movie_language");
            return (Criteria) this;
        }

        public Criteria andMovie_typeIsNull() {
            addCriterion("movie_type is null");
            return (Criteria) this;
        }

        public Criteria andMovie_typeIsNotNull() {
            addCriterion("movie_type is not null");
            return (Criteria) this;
        }

        public Criteria andMovie_typeEqualTo(Integer value) {
            addCriterion("movie_type =", value, "movie_type");
            return (Criteria) this;
        }

        public Criteria andMovie_typeNotEqualTo(Integer value) {
            addCriterion("movie_type <>", value, "movie_type");
            return (Criteria) this;
        }

        public Criteria andMovie_typeGreaterThan(Integer value) {
            addCriterion("movie_type >", value, "movie_type");
            return (Criteria) this;
        }

        public Criteria andMovie_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("movie_type >=", value, "movie_type");
            return (Criteria) this;
        }

        public Criteria andMovie_typeLessThan(Integer value) {
            addCriterion("movie_type <", value, "movie_type");
            return (Criteria) this;
        }

        public Criteria andMovie_typeLessThanOrEqualTo(Integer value) {
            addCriterion("movie_type <=", value, "movie_type");
            return (Criteria) this;
        }

        public Criteria andMovie_typeIn(List<Integer> values) {
            addCriterion("movie_type in", values, "movie_type");
            return (Criteria) this;
        }

        public Criteria andMovie_typeNotIn(List<Integer> values) {
            addCriterion("movie_type not in", values, "movie_type");
            return (Criteria) this;
        }

        public Criteria andMovie_typeBetween(Integer value1, Integer value2) {
            addCriterion("movie_type between", value1, value2, "movie_type");
            return (Criteria) this;
        }

        public Criteria andMovie_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("movie_type not between", value1, value2, "movie_type");
            return (Criteria) this;
        }

        public Criteria andMovie_ratingIsNull() {
            addCriterion("movie_rating is null");
            return (Criteria) this;
        }

        public Criteria andMovie_ratingIsNotNull() {
            addCriterion("movie_rating is not null");
            return (Criteria) this;
        }

        public Criteria andMovie_ratingEqualTo(Integer value) {
            addCriterion("movie_rating =", value, "movie_rating");
            return (Criteria) this;
        }

        public Criteria andMovie_ratingNotEqualTo(Integer value) {
            addCriterion("movie_rating <>", value, "movie_rating");
            return (Criteria) this;
        }

        public Criteria andMovie_ratingGreaterThan(Integer value) {
            addCriterion("movie_rating >", value, "movie_rating");
            return (Criteria) this;
        }

        public Criteria andMovie_ratingGreaterThanOrEqualTo(Integer value) {
            addCriterion("movie_rating >=", value, "movie_rating");
            return (Criteria) this;
        }

        public Criteria andMovie_ratingLessThan(Integer value) {
            addCriterion("movie_rating <", value, "movie_rating");
            return (Criteria) this;
        }

        public Criteria andMovie_ratingLessThanOrEqualTo(Integer value) {
            addCriterion("movie_rating <=", value, "movie_rating");
            return (Criteria) this;
        }

        public Criteria andMovie_ratingIn(List<Integer> values) {
            addCriterion("movie_rating in", values, "movie_rating");
            return (Criteria) this;
        }

        public Criteria andMovie_ratingNotIn(List<Integer> values) {
            addCriterion("movie_rating not in", values, "movie_rating");
            return (Criteria) this;
        }

        public Criteria andMovie_ratingBetween(Integer value1, Integer value2) {
            addCriterion("movie_rating between", value1, value2, "movie_rating");
            return (Criteria) this;
        }

        public Criteria andMovie_ratingNotBetween(Integer value1, Integer value2) {
            addCriterion("movie_rating not between", value1, value2, "movie_rating");
            return (Criteria) this;
        }

        public Criteria andMovie_quoteIsNull() {
            addCriterion("movie_quote is null");
            return (Criteria) this;
        }

        public Criteria andMovie_quoteIsNotNull() {
            addCriterion("movie_quote is not null");
            return (Criteria) this;
        }

        public Criteria andMovie_quoteEqualTo(String value) {
            addCriterion("movie_quote =", value, "movie_quote");
            return (Criteria) this;
        }

        public Criteria andMovie_quoteNotEqualTo(String value) {
            addCriterion("movie_quote <>", value, "movie_quote");
            return (Criteria) this;
        }

        public Criteria andMovie_quoteGreaterThan(String value) {
            addCriterion("movie_quote >", value, "movie_quote");
            return (Criteria) this;
        }

        public Criteria andMovie_quoteGreaterThanOrEqualTo(String value) {
            addCriterion("movie_quote >=", value, "movie_quote");
            return (Criteria) this;
        }

        public Criteria andMovie_quoteLessThan(String value) {
            addCriterion("movie_quote <", value, "movie_quote");
            return (Criteria) this;
        }

        public Criteria andMovie_quoteLessThanOrEqualTo(String value) {
            addCriterion("movie_quote <=", value, "movie_quote");
            return (Criteria) this;
        }

        public Criteria andMovie_quoteLike(String value) {
            addCriterion("movie_quote like", value, "movie_quote");
            return (Criteria) this;
        }

        public Criteria andMovie_quoteNotLike(String value) {
            addCriterion("movie_quote not like", value, "movie_quote");
            return (Criteria) this;
        }

        public Criteria andMovie_quoteIn(List<String> values) {
            addCriterion("movie_quote in", values, "movie_quote");
            return (Criteria) this;
        }

        public Criteria andMovie_quoteNotIn(List<String> values) {
            addCriterion("movie_quote not in", values, "movie_quote");
            return (Criteria) this;
        }

        public Criteria andMovie_quoteBetween(String value1, String value2) {
            addCriterion("movie_quote between", value1, value2, "movie_quote");
            return (Criteria) this;
        }

        public Criteria andMovie_quoteNotBetween(String value1, String value2) {
            addCriterion("movie_quote not between", value1, value2, "movie_quote");
            return (Criteria) this;
        }

        public Criteria andMovie_cover_picIsNull() {
            addCriterion("movie_cover_pic is null");
            return (Criteria) this;
        }

        public Criteria andMovie_cover_picIsNotNull() {
            addCriterion("movie_cover_pic is not null");
            return (Criteria) this;
        }

        public Criteria andMovie_cover_picEqualTo(String value) {
            addCriterion("movie_cover_pic =", value, "movie_cover_pic");
            return (Criteria) this;
        }

        public Criteria andMovie_cover_picNotEqualTo(String value) {
            addCriterion("movie_cover_pic <>", value, "movie_cover_pic");
            return (Criteria) this;
        }

        public Criteria andMovie_cover_picGreaterThan(String value) {
            addCriterion("movie_cover_pic >", value, "movie_cover_pic");
            return (Criteria) this;
        }

        public Criteria andMovie_cover_picGreaterThanOrEqualTo(String value) {
            addCriterion("movie_cover_pic >=", value, "movie_cover_pic");
            return (Criteria) this;
        }

        public Criteria andMovie_cover_picLessThan(String value) {
            addCriterion("movie_cover_pic <", value, "movie_cover_pic");
            return (Criteria) this;
        }

        public Criteria andMovie_cover_picLessThanOrEqualTo(String value) {
            addCriterion("movie_cover_pic <=", value, "movie_cover_pic");
            return (Criteria) this;
        }

        public Criteria andMovie_cover_picLike(String value) {
            addCriterion("movie_cover_pic like", value, "movie_cover_pic");
            return (Criteria) this;
        }

        public Criteria andMovie_cover_picNotLike(String value) {
            addCriterion("movie_cover_pic not like", value, "movie_cover_pic");
            return (Criteria) this;
        }

        public Criteria andMovie_cover_picIn(List<String> values) {
            addCriterion("movie_cover_pic in", values, "movie_cover_pic");
            return (Criteria) this;
        }

        public Criteria andMovie_cover_picNotIn(List<String> values) {
            addCriterion("movie_cover_pic not in", values, "movie_cover_pic");
            return (Criteria) this;
        }

        public Criteria andMovie_cover_picBetween(String value1, String value2) {
            addCriterion("movie_cover_pic between", value1, value2, "movie_cover_pic");
            return (Criteria) this;
        }

        public Criteria andMovie_cover_picNotBetween(String value1, String value2) {
            addCriterion("movie_cover_pic not between", value1, value2, "movie_cover_pic");
            return (Criteria) this;
        }

        public Criteria andRelease_timeIsNull() {
            addCriterion("release_time is null");
            return (Criteria) this;
        }

        public Criteria andRelease_timeIsNotNull() {
            addCriterion("release_time is not null");
            return (Criteria) this;
        }

        public Criteria andRelease_timeEqualTo(Date value) {
            addCriterion("release_time =", value, "release_time");
            return (Criteria) this;
        }

        public Criteria andRelease_timeNotEqualTo(Date value) {
            addCriterion("release_time <>", value, "release_time");
            return (Criteria) this;
        }

        public Criteria andRelease_timeGreaterThan(Date value) {
            addCriterion("release_time >", value, "release_time");
            return (Criteria) this;
        }

        public Criteria andRelease_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("release_time >=", value, "release_time");
            return (Criteria) this;
        }

        public Criteria andRelease_timeLessThan(Date value) {
            addCriterion("release_time <", value, "release_time");
            return (Criteria) this;
        }

        public Criteria andRelease_timeLessThanOrEqualTo(Date value) {
            addCriterion("release_time <=", value, "release_time");
            return (Criteria) this;
        }

        public Criteria andRelease_timeIn(List<Date> values) {
            addCriterion("release_time in", values, "release_time");
            return (Criteria) this;
        }

        public Criteria andRelease_timeNotIn(List<Date> values) {
            addCriterion("release_time not in", values, "release_time");
            return (Criteria) this;
        }

        public Criteria andRelease_timeBetween(Date value1, Date value2) {
            addCriterion("release_time between", value1, value2, "release_time");
            return (Criteria) this;
        }

        public Criteria andRelease_timeNotBetween(Date value1, Date value2) {
            addCriterion("release_time not between", value1, value2, "release_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeEqualTo(Date value) {
            addCriterion("update_time =", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThan(Date value) {
            addCriterion("update_time >", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThan(Date value) {
            addCriterion("update_time <", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIn(List<Date> values) {
            addCriterion("update_time in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("flag is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("flag is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(Integer value) {
            addCriterion("flag =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(Integer value) {
            addCriterion("flag <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(Integer value) {
            addCriterion("flag >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("flag >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(Integer value) {
            addCriterion("flag <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(Integer value) {
            addCriterion("flag <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<Integer> values) {
            addCriterion("flag in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<Integer> values) {
            addCriterion("flag not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(Integer value1, Integer value2) {
            addCriterion("flag between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("flag not between", value1, value2, "flag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_movie
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_movie
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}