package com.gaofen.dianying.persistent.entity;

import java.util.Date;

public class TMovieBaiduyun extends TMovieBaiduyunKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_baiduyun.movie_id
     *
     * @mbggenerated
     */
    private Integer movie_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_baiduyun.movie_baiduyun_link_info
     *
     * @mbggenerated
     */
    private String movie_baiduyun_link_info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_baiduyun.movie_baiduyun_link_back_info
     *
     * @mbggenerated
     */
    private String movie_baiduyun_link_back_info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_baiduyun.create_time
     *
     * @mbggenerated
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_baiduyun.update_time
     *
     * @mbggenerated
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_baiduyun.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_baiduyun.movie_id
     *
     * @return the value of t_movie_baiduyun.movie_id
     *
     * @mbggenerated
     */
    public Integer getMovie_id() {
        return movie_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_baiduyun.movie_id
     *
     * @param movie_id the value for t_movie_baiduyun.movie_id
     *
     * @mbggenerated
     */
    public void setMovie_id(Integer movie_id) {
        this.movie_id = movie_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_baiduyun.movie_baiduyun_link_info
     *
     * @return the value of t_movie_baiduyun.movie_baiduyun_link_info
     *
     * @mbggenerated
     */
    public String getMovie_baiduyun_link_info() {
        return movie_baiduyun_link_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_baiduyun.movie_baiduyun_link_info
     *
     * @param movie_baiduyun_link_info the value for t_movie_baiduyun.movie_baiduyun_link_info
     *
     * @mbggenerated
     */
    public void setMovie_baiduyun_link_info(String movie_baiduyun_link_info) {
        this.movie_baiduyun_link_info = movie_baiduyun_link_info == null ? null : movie_baiduyun_link_info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_baiduyun.movie_baiduyun_link_back_info
     *
     * @return the value of t_movie_baiduyun.movie_baiduyun_link_back_info
     *
     * @mbggenerated
     */
    public String getMovie_baiduyun_link_back_info() {
        return movie_baiduyun_link_back_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_baiduyun.movie_baiduyun_link_back_info
     *
     * @param movie_baiduyun_link_back_info the value for t_movie_baiduyun.movie_baiduyun_link_back_info
     *
     * @mbggenerated
     */
    public void setMovie_baiduyun_link_back_info(String movie_baiduyun_link_back_info) {
        this.movie_baiduyun_link_back_info = movie_baiduyun_link_back_info == null ? null : movie_baiduyun_link_back_info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_baiduyun.create_time
     *
     * @return the value of t_movie_baiduyun.create_time
     *
     * @mbggenerated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_baiduyun.create_time
     *
     * @param create_time the value for t_movie_baiduyun.create_time
     *
     * @mbggenerated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_baiduyun.update_time
     *
     * @return the value of t_movie_baiduyun.update_time
     *
     * @mbggenerated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_baiduyun.update_time
     *
     * @param update_time the value for t_movie_baiduyun.update_time
     *
     * @mbggenerated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_baiduyun.flag
     *
     * @return the value of t_movie_baiduyun.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_baiduyun.flag
     *
     * @param flag the value for t_movie_baiduyun.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}