package com.gaofen.dianying.persistent.entity;

public class TMovieDetailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_detail.movie_detail_id
     *
     * @mbggenerated
     */
    private Integer movie_detail_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_detail.movie_detail_id
     *
     * @return the value of t_movie_detail.movie_detail_id
     *
     * @mbggenerated
     */
    public Integer getMovie_detail_id() {
        return movie_detail_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_detail.movie_detail_id
     *
     * @param movie_detail_id the value for t_movie_detail.movie_detail_id
     *
     * @mbggenerated
     */
    public void setMovie_detail_id(Integer movie_detail_id) {
        this.movie_detail_id = movie_detail_id;
    }
}