package com.gaofen.dianying.persistent.entity;

public class TMovieBaiduyunKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_baiduyun.movie_baiduyun_id
     *
     * @mbggenerated
     */
    private Integer movie_baiduyun_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_baiduyun.movie_baiduyun_id
     *
     * @return the value of t_movie_baiduyun.movie_baiduyun_id
     *
     * @mbggenerated
     */
    public Integer getMovie_baiduyun_id() {
        return movie_baiduyun_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_baiduyun.movie_baiduyun_id
     *
     * @param movie_baiduyun_id the value for t_movie_baiduyun.movie_baiduyun_id
     *
     * @mbggenerated
     */
    public void setMovie_baiduyun_id(Integer movie_baiduyun_id) {
        this.movie_baiduyun_id = movie_baiduyun_id;
    }
}