package com.gaofen.dianying.persistent.entity;

public class TMovieExcellentCommentWithBLOBs extends TMovieExcellentComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_excellent_comment.movie_excellent_comment
     *
     * @mbggenerated
     */
    private String movie_excellent_comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_excellent_comment.movie_excellent_comment
     *
     * @return the value of t_movie_excellent_comment.movie_excellent_comment
     *
     * @mbggenerated
     */
    public String getMovie_excellent_comment() {
        return movie_excellent_comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_excellent_comment.movie_excellent_comment
     *
     * @param movie_excellent_comment the value for t_movie_excellent_comment.movie_excellent_comment
     *
     * @mbggenerated
     */
    public void setMovie_excellent_comment(String movie_excellent_comment) {
        this.movie_excellent_comment = movie_excellent_comment == null ? null : movie_excellent_comment.trim();
    }
}