package com.gaofen.dianying.persistent.entity;

public class TMovieExcellentCommentKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_excellent_comment.movie_excellent_id
     *
     * @mbggenerated
     */
    private Integer movie_excellent_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_excellent_comment.movie_excellent_id
     *
     * @return the value of t_movie_excellent_comment.movie_excellent_id
     *
     * @mbggenerated
     */
    public Integer getMovie_excellent_id() {
        return movie_excellent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_excellent_comment.movie_excellent_id
     *
     * @param movie_excellent_id the value for t_movie_excellent_comment.movie_excellent_id
     *
     * @mbggenerated
     */
    public void setMovie_excellent_id(Integer movie_excellent_id) {
        this.movie_excellent_id = movie_excellent_id;
    }
}