package com.gaofen.dianying.persistents.mapper;

import com.gaofen.dianying.persistents.entity.TMovieConfig;
import com.gaofen.dianying.persistents.entity.TMovieConfigExample;
import com.gaofen.dianying.persistents.entity.TMovieConfigKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TMovieConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_config
     *
     * @mbggenerated
     */
    int countByExample(TMovieConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_config
     *
     * @mbggenerated
     */
    int deleteByExample(TMovieConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TMovieConfigKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_config
     *
     * @mbggenerated
     */
    int insert(TMovieConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_config
     *
     * @mbggenerated
     */
    int insertSelective(TMovieConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_config
     *
     * @mbggenerated
     */
    List<TMovieConfig> selectByExample(TMovieConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_config
     *
     * @mbggenerated
     */
    TMovieConfig selectByPrimaryKey(TMovieConfigKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TMovieConfig record, @Param("example") TMovieConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TMovieConfig record, @Param("example") TMovieConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TMovieConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TMovieConfig record);
}