package com.gaofen.dianying.persistents.mapper;

import com.gaofen.dianying.persistents.entity.TMoviePhotos;
import com.gaofen.dianying.persistents.entity.TMoviePhotosExample;
import com.gaofen.dianying.persistents.entity.TMoviePhotosKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMoviePhotosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_photos
     *
     * @mbggenerated
     */
    int countByExample(TMoviePhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_photos
     *
     * @mbggenerated
     */
    int deleteByExample(TMoviePhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_photos
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TMoviePhotosKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_photos
     *
     * @mbggenerated
     */
    int insert(TMoviePhotos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_photos
     *
     * @mbggenerated
     */
    int insertSelective(TMoviePhotos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_photos
     *
     * @mbggenerated
     */
    List<TMoviePhotos> selectByExample(TMoviePhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_photos
     *
     * @mbggenerated
     */
    TMoviePhotos selectByPrimaryKey(TMoviePhotosKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_photos
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TMoviePhotos record, @Param("example") TMoviePhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_photos
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TMoviePhotos record, @Param("example") TMoviePhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_photos
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TMoviePhotos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_photos
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TMoviePhotos record);
}