package com.gaofen.dianying.persistents.mapper;

import com.gaofen.dianying.persistents.entity.TMovieComments;
import com.gaofen.dianying.persistents.entity.TMovieCommentsExample;
import com.gaofen.dianying.persistents.entity.TMovieCommentsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMovieCommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_comments
     *
     * @mbggenerated
     */
    int countByExample(TMovieCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_comments
     *
     * @mbggenerated
     */
    int deleteByExample(TMovieCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_comments
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TMovieCommentsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_comments
     *
     * @mbggenerated
     */
    int insert(TMovieComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_comments
     *
     * @mbggenerated
     */
    int insertSelective(TMovieComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_comments
     *
     * @mbggenerated
     */
    List<TMovieComments> selectByExample(TMovieCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_comments
     *
     * @mbggenerated
     */
    TMovieComments selectByPrimaryKey(TMovieCommentsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_comments
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TMovieComments record, @Param("example") TMovieCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_comments
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TMovieComments record, @Param("example") TMovieCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_comments
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TMovieComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_movie_comments
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TMovieComments record);
}